### PR TITLE
Move ZFS Admin Guide out of staging & convert it + others to DocBook 5

### PR DESCRIPTION
**Pull request by melloc**
These changes move the ZFS Admin Guide out of staging and into raw, and update them from SolBook to DocBook 5.

### CODE REVIEW

**Comment by madwizard** [comment]
Cody, thank you. That's gonna let us work on updating it.

Damian

**Comment by rmustacc** [comment]
@melloc with the conversion to docbook 5, I presume the janky tools in here no longer honor it and we need to get the new build process in place. Is that right?

**Comment by melloc** [comment]
@rmustacc Yep, that's right. If you want, you can wait to pull this in until I have that ready to be pulled, too. I mostly put this up so that @madwizard could work on top of it.

**Comment by melloc** [comment]
(Note that it can be built with dblatex currently.)

**Comment by melloc** [comment]
@madwizard I've pushed to my branch the XSLT to generate web pages. You can generate it by running:

```
mvn xml:transform
```

I've also updated the `make check` target to check the validity of the XML using the DocBook 5 RelaxNG schema.

Saxon has a node.js XSLT 2.0 library available, so I might take a look at using that instead of their Java one, but I haven't found a good RelaxNG validation tool besides Jing, yet. (xmllint's `--relaxng` routinely reported the wrong issue and seems to get confused easily.)

**Comment by melloc** [comment]
(I've also pushed the converted DTrace guide, and the MPT guide. There are still some things that need to be cleaned up in the MDB and WDD guides.)

**Comment by melloc** [comment]
I just pushed some updates to the build process, and the converted MDB and WDD guides. There are a handful of small improvements I'd like to make at some point (like adding clickable anchors to sections and maybe renaming some sections' IDs so that they have better link names), but I think that things are at a good point right now. You can see the current output here:

- [MDB](http://us-east.manta.joyent.com/cody.mello/public/mdb/index.html)
- [DTrace](http://us-east.manta.joyent.com/cody.mello/public/dtrace/index.html)
- [WDD](http://us-east.manta.joyent.com/cody.mello/public/wdd/index.html)
- [ZFS](http://us-east.manta.joyent.com/cody.mello/public/zfs-admin/index.html)
- [LGRPS](http://us-east.manta.joyent.com/cody.mello/public/lgrps/index.html)

**Comment by melloc** [comment]
It would probably also be good if someone could check out the changes locally and make sure they're able to build without issue. I'm pretty sure that I've checked everything in, and have no special local requirements. I'll update the README to show the programs that need to be installed, but they are:

- maven (and java)
- image magick
- dblatex (and latex)

There might be some latex packages that also need to be installed. I'll set up a clean environment and try building there.

**Comment by melloc** [comment]
The set of packages needed are:

- GNU make (gmake in pkgsrc)
- Maven (apache-maven in pkgsrc)
- dblatex (dblatex in pkgsrc)
- epstopdf conversion tool (tex-epstopdf in pkgsrc)
- texlive packages (texlive-collection-fontsrecommended, texlive-collection-latexrecommended, texlive-collection-latexextra in pkgsrc)
- cyrillic fonts (tex-cyrillic in pkgsrc)

I'll update the README to mention this.

**Comment by melloc** [comment]
I've updated the `Makefile` to have an `html` target to build just the HTML pages. This will allow people who don't have LaTeX installed to preview changes.

**Comment by melloc** [comment]
These commits have now all been merged.

**Pull request closed without merging**
